version: '3.9'
services:
  mysql-kc:
    image: mysql:8.0.27
    ports:
      - "3377:3306"
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: keycloak_db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak-w:
    image: quay.io/keycloak/keycloak:22.0.4
    command: start-dev
    ports:
      - "9081:8080"
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN : admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:mysql://mysql-kc:3306/keycloak_db
      KC_FEATURES: token-exchange,admin-fine-grained-authz
      #      PROXY_ADDRESS_FORWARDING: 'true' // deploying on vps server
      #      KC_PROXY: edge // deploying on vps server
      KC_HOSTNAME: localhost
    #      KC_HOSTNAME_STRICT_HTTPS: 'true' // deploying on vps server
    depends_on:
      - mysql-kc
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:

